# services:
#   qdrant:
#     image: qdrant/qdrant:latest
#     ports:
#       - "6333:6333"
#       - "6334:6334"
#     volumes:
#       - qdrant_storage:/qdrant/storage
#     environment:
#       - QDRANT__SERVICE__HTTP_PORT=6333
#     restart: unless-stopped

#   app:
#     build:
#       context: .
#       dockerfile: docker/app.dockerfile
#     ports:
#       - "8000:8000"
#     env_file:
#       - .env
#     environment:
#       QDRANT_HOST: qdrant
#       QDRANT_PORT: 6333
#       OLLAMA_BASE_URL: http://host.docker.internal:11434
#     extra_hosts:
#       - "host.docker.internal:host-gateway"
#     volumes:
#       - ./data:/app/data
#       - ./logs:/app/logs
#     depends_on:
#       qdrant:
#         condition: service_started
#     restart: unless-stopped

# volumes:
#   qdrant_storage:

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333" # Puerto HTTP para consultas
      - "6334:6334" # Pueto gRPC (comunicación interna rapida)
    volumes: 
      - qdrant_storage:/qdrant/storage #Aqui se guardan los datos en disco
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
    restart: unless-stopped

volumes:
  qdrant_storage: # Volumen para persistir los datos en la base de datos