name: Test Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Hola
        run: echo "Hola desde el servidor"

      - name: Mostrar carpeta
        run: Get-Location

      - name: Listar archivos
        run: Get-ChildItem -Force
